### ISSUE TITLE
R7RS large support

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#105]
This is an on-going process.
See: http://trac.sacrideo.us/wg/wiki/WG2Dockets

**Comment by kozross** [comment]
There has since been a [Red Edition release][1]. With that in mind, here's a 'to-support' list:

- [X] SRFI 1 (list library, as ``(scheme list)``)
- [X] SRFI 133 (vector library, as ``(scheme vector)``)
- [X] SRFI 132 (sorting library, as ``(scheme sort)``)
- [ ] SRFI 113 (sets and bags, as ``(scheme set)``)
- [ ] SRFI 12 (character sets, as ``(scheme charset)``)
- [ ] SRFI 125 (intermediate hash tables, as ``(scheme hash-table)``)
- [ ] SRFI 116 (immutable lists, as ``(scheme ilist)``)
- [ ] SRFI 101 (purely-functional random-access pairs and lists, as ``(scheme rlist)``)
- [ ] SRFI 134 (immutable deques, as ``(scheme ideque)``)
- [ ] SRFI 135 (immutable texts, as ``(scheme text)``) 
- [X] SRFI 121 (generators, as ``(scheme generator)``)
- [ ] SRFI 127 (lazy sequences, as ``(scheme lseq)``)
- [ ] SRFI 41 (streams, as ``(scheme stream)``)
- [X] SRFI 111 (boxes, as ``(scheme box)``)
- [ ] SRFI 124 (ephemerons, as ``(scheme ephemeron)``)
- [X] SRFI 128 (reduced comparators, as ``(scheme comparator)``)

[1]: http://trac.sacrideo.us/wg/wiki/RedEdition

**Comment by kozross** [comment]
Now, my 10 (New Zealand) cents on these:

- Having *both* sets and bags *and* hash tables available strikes me as rather odd. While I understand that bags are multisets (which *can* be implemented on top of hash tables, but not efficiently), it seems odd to provide *both* of these. Realistically, SRFI 113 shouldn't pose a problem to provide, but I've yet to see a *single* time when a bag was the right data structure for the job, so I wouldn't rush.
- SRFI 12 should wait until we have UTF-8 support. Having this implemented prior to taking care of this seems premature at best.
- SRFI 125 is a library I'm happy to implement. The stock implementation of SRFI 69 has some *serious* performance issues, and I happen to know a little about how to implement hash tables, and would love the challenge. That being said, if we do implement SRFI 125, I would suggest scrapping SRFI 69.
- SRFI 116, 101, 134 and 135 all rely on immutability at the data structure level. I remember you mentioning something about this not being something Cyclone can do yet, and even if we could fake it, there's considerable performance gains to be achieved from immutability. These need further work, probably to Cyclone's core, and thus, are probably not something we can get soon.
- SRFI 127 is a hop, step and a jump away from SRFI 121, which I've just implemented. Happy to do that, and it'll be easy.
- SRFI 41 is ... a nightmare given form. The reference implementation is based on R6RS, and leans on several bits of macrology that R7RS's standard does not supply. Out of all the Schemes I've looked into, only Larceny has an implementation of this, and for very good reason. Prior to implementing SRFI 121, I thought I'd give this a go. Even coming from a Haskell background and having a non-trivial amount of data structure and algorithm training, this made me cry. While streams are very cool, and can do amazing things, there's a bunch of issues there, including some which require changes in Cyclone's core. Furthermore, from what I gather, some of it is actually *impossible* (or very nearly) to do in R7RS. Not sure what the Red Edition committee were thinking when they voted that through, honestly.
- SRFI 124 is a semi-precursor to SRFI 125; the former allows the latter to be much more GC-efficient. It is also likely gonna have to be something which integrates tightly with Cyclone's core. While I am no expert on garbage collection, I'm not *entirely* sure whether this has a sufficiently-good use case. I welcome feedback on this, though, as I am definitely ignorant on this front.

**Comment by kozross** [comment]
It is also worth noting that the Red Edition is not (yet) definitive - a few things still need reballoting, so this list may yet grow.

**Comment by kozross** [comment]
- For aliases, this is easy: just create a new file ``scheme/list.sld``, have it ``(import (srfi 1))``, then re-export everything it provides. It's tedious, but very easy.
- SRFI 125's *interface* doesn't inherently solve any of the above (they're all implementation issues). However, one thing about it that does help is that its interface permits better implementations. I will discuss this more in a separate issue, because this is fairly non-trivial and requires some knowledge of Cyclone's internals, which I don't have.
- SRFI 41 is *already* a revision, to address some serious semantic issues in SRFI 40. The main reason why it hasn't seen as much adoption as SRFI 121, 127 and a few others is due to its sheer complexity, and the fact that most people writing Scheme don't actually need the full power of streams to do what they want. While having laziness a la Haskell available is certainly *nice* from a theoretical point of view, it's hard to implement and generally isn't very efficient (unless you do *serious* work optimizing them in the core, as Haskell has done).
- SRFI 124 can be done with a 'no-op' implementation: the standard does not require any semantic behaviour from ephemerons. In fact, a no-op implementation is already provided by the SRFI document itself. We can use that to fill in for now - that would also be quite easy to do.

I will mark a few of the entries as 'pending implementation', and we can use this thread for a general discussion of Red Edition implementation issues that don't warrant their own threads.

**Comment by justinethier** [comment]
Closing, future SRFI support will be added via winds packages.
