### ISSUE TITLE
Relationship between cyclone-bootstrap and cyclone

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#166]
This is mostly prompted by [this][1] - I'm a little confused about the difference between these two. Furthermore, I cannot tell how the cyclone build process gets a hold of cyclone-bootstrap. Normally, this would be done using a git submodule, but I can't see one of those here. Could you please let me know how this works?

[1]: https://github.com/justinethier/cyclone/issues/165#issuecomment-276383329

**Comment by justinethier** [comment]
Sure. Basically, all of the `.c` modules generated by compiled Scheme files need to be made available in order for someone to compile Cyclone from scratch on a new machine. The alternative is to make binaries available but then you need a different set for different platforms, etc...

To make that happen, cyclone-bootstrap contains the compiled version of everything in the main cyclone repo. The idea was to try to keep this repo clean instead of storing everything in a single repo. 

Sometimes when working on the compiler it is convenient to use the bootstrap repo to do builds and installs. This is more of a concern when changing compiler internals and less of a concern when working on other libraries such as SRFI's. There isn't any linkage between the 2 except for a convenience script `sync.sh` that works if you place both repos in the same parent directory.

Does that help? Or does this approach still seem a little crazy? :)

**Comment by kozross** [comment]
Yeah, this makes sense. A few other implementations of Scheme provide bootstrap compilers (Guile comes to mind), so this isn't as mad as it seems. Thanks for clarifying, though.
