### ISSUE TITLE
read-line includes trailing newline

### ISSUE THREAD

**Issue by wasamasa** [justinethier/cyclone#216]
I'm writing a simple REPL for fun and noticed that Cyclone is the only R7RS implementation where `read-line` includes the trailing newline.  The fault appears to lie within `cyc_io_read_line`, but I can't get it to behave as expected with the following change in `runtime.c`, otherwise I'd have submitted a PR:

```diff
@@ -6183,6 +6183,7 @@ object Cyc_io_read_line(void *data, object cont, object port)
   set_thread_blocked(data, cont);
   errno = 0;
   if (fgets(buf, 1023, stream) != NULL) {
+    buf[strcspn(buf, "\r\n")] = '\0';
     make_string(s, buf);
     return_thread_runnable(data, &s);
   } else {
```

**Comment by justinethier** [comment]
@wasamasa - Thanks for the bug report! I think this should fix the problem...

**Comment by wasamasa** [comment]
Hm, the reason I picked `strcspn` is because that way you can deal with both `\r` and `\n`.  The standard tells pretty clearly "For the purpose of this procedure, an end of line consists of either a linefeed character, a carriage return character, or a sequence of a carriage return character followed by a linefeed character.".  Merely detecting `\n` does not fulfill that requirement.

**Comment by justinethier** [comment]
@wasamasa - Good point, thanks! Nothing against the `strcspn` change, I used something different just to attempt to be more efficient. I'm thinking it should be possible to test characters before the `\n` and decrement `len` until it does not point to a linefeed character. 

I'll try to find some time for that later today, otherwise if you would like to submit a pull request that would be great, too.

**Comment by wasamasa** [comment]
Thanks!
