### ISSUE TITLE
docs: adding more 'why' to the 'how'

### ISSUE THREAD

**Issue by bentxt** [justinethier/cyclone#348]
hi
There is a great introduction text and feature list about cyclone on the website https://justinethier.github.io/cyclone/. It describes in detail how cyclone is built, and points out its technical merits.

There are multiple great scheme implementations out there. So I would find it interesting to know if there was a specific reason(s) why there is cyclone. 

For example in the introductionary text of Sagittarius scheme there is the following description: [...] There are a lot of Scheme implementations and they have different strong and weak points. Sagittarius focuses on "Flexibility" and "Easy to Use". [...]
http://ktakashi.github.io/sagittarius-online-ref/section11.html

From a user perspective: Why should you use cyclone (for x y z)?

thanks
ben

**Comment by justinethier** [comment]
@bentxt Well, besides the technical merits Cyclone was written specifically to target the R7RS; both implementing that spec and being (mostly) written in it. So it is a good choice for writing new Scheme if you want to use R7RS since it also provides modern features (multi-threading, C FFI, Unicode, small/hackable compiler, etc) and is reasonably fast.
