### ISSUE TITLE
example ffi

### ISSUE THREAD

**Issue by javan-z** [justinethier/cyclone#381]
Trying to make a small example of using ffi to get curl_version
Its not entirely clear how to do this

**Comment by justinethier** [comment]
Need to put together better documentation for this, but our [Package Manager](https://github.com/cyclone-scheme/cyclone-winds) has a [CURL package](https://github.com/cyclone-scheme/curl) that may help. See: https://github.com/cyclone-scheme/curl/blob/master/cyclone/curl.sld#L578

There is also an [FFI library](https://github.com/justinethier/cyclone/blob/master/docs/api/cyclone/foreign.md) on `master` and in our next release that makes this easier. Here are some [usage examples](https://github.com/justinethier/cyclone/blob/master/libs/test-foreign.scm).

**Comment by arthurmaciel** [comment]
@justinethier, it is really a nice work! I Congrats! 

Using the test examples as a reference, could you please tell me where the numbers on C variables come from? What is the logic to get specifically 85 and 91 [here](https://github.com/justinethier/cyclone/blob/master/libs/test-foreign.scm#L31) and where I can read more about it?

**Comment by justinethier** [comment]
Thanks @arthurmaciel :)

That's a good question that gets deep into the internals. Basically Scheme lets you use all sorts of characters in a variable name (identifier) that would not be legal in other languages such as C: `-!?%$` etc. So when code is compiled to C each identifier is "mangled" by replacing such characters with other characters that are legal for an identifier in C. That is why you see things like `_91` in the C identifier because that sequence replaced a char in the Scheme identifier. You usually would not have to worry about this when using the FFI but it could come up, depending on what your code needs to accomplish.

**Comment by javan-z** [comment]
Thanks! Very helpful!

**Comment by arthurmaciel** [comment]
Thanks, Justin!

I was wondering more about 85 and 91 themselves. Why not 72 and 109, or any
other pair? I didn't find any relation, for example, to the ASCII table for
translating "-" into 45. Is there a fixed-value translation table?

Best,
Arthur


Em ter, 26 de mai de 2020 23:50, Justin Ethier <notifications@github.com>
escreveu:

**Comment by justinethier** [comment]
@arthurmaciel Good question and I don't remember offhand but this is what is being called by the compiler:

    cyclone> (mangle '*my-global*)
    "_85my_91global_85"

Looks like the call to `char->natural` is doing that; see:

https://github.com/justinethier/cyclone/blob/master/scheme/cyclone/util.sld#L346
https://github.com/justinethier/cyclone/blob/master/scheme/cyclone/util.sld#L694

**Comment by arthurmaciel** [comment]
Ah, great! So "-" is 91, due to 45 (of ASCII table) + 1  :)

Really instructive! It is always good to know more about Cyclone internals. Thanks, @justinethier!
