### ISSUE TITLE
Add import functionality to the interpreter

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#87]
The interpreter needs to be able to `import` libraries. 

But how will this work under the hood? It would be nice if the compiled code could be loaded, but that might require more than the object file we have now. The code might have to be compiled into a library as well, such that it can be loaded at runtime. It might also require `icyc` to load any dependencies as well.

**Comment by justinethier** [comment]
Apparently the place to start is to build libraries as SO (shared object) files and use dlopen(3) and dlsym(3) to load them.

**Comment by justinethier** [comment]
Should make a branch using shared objects `.so` instead of object `.o` libraries and measure the performance difference.

**Comment by justinethier** [comment]
From the CHICKEN wikipedia article:

> In order to make cross-compilation possible for Scheme code, CHICKEN imposes a model of separate compilation: A compiled module consists of two shared libraries. One library contains the actual code which will be used at runtime (compiled for the target platform), and the other is an "import module", which will be used to load the code which runs at compile-time (on the host platform), such as procedural macro code.

There are a lot of possibilities that can be unlocked by using dynamic linking. This could even improve macro performance since all macros would be compiled (cyclone would load the "import module" at compile time).

The only question is what the performance impact will be of using position independent code (PIC).

**Comment by kozross** [comment]
I don't think performance should be a concern at the REPL. The main way I (and I'm sure many others) use it is to test and play around, and thus, if we incur some performance loss by loading a library at the REPL rather than compiling it then running it, I'd say that's acceptable.

Furthermore, the penalty is [not exactly staggering][1] in the first place. There are [some additional (if older) results][2] which basically state the same thing.

[1]: http://stackoverflow.com/questions/15861759/how-much-overhead-can-the-fpic-flag-add
[2]: https://gcc.gnu.org/ml/gcc/2004-06/msg01956.html

**Comment by justinethier** [comment]
The performance difference would be at the compiler and REPL, though. All modules would need to be compiled as PIC so they could be loaded dynamically.

You could test by adding the flag to both lines in [`Makefile.config`](https://github.com/justinethier/cyclone-bootstrap/blob/master/Makefile.config#L8) and recompiling.

**Comment by kozross** [comment]
Do you have some benchmarks I could test this on? Would the ones by ecraven be suitable?

**Comment by justinethier** [comment]
Yes, those are the best ones: https://github.com/ecraven/r7rs-benchmarks

**Comment by kozross** [comment]
OK, I just ran the ecraven benchmarks, using freshly-build Cyclones from source, both with the PIC flags and without. I've attached a diff of the two outputs (this is a diff-formatted file, the .txt extension is because Github won't let me upload .diffs). tl;dr version below:

* earley loses under PIC (~13s slower).
* mperm wins under PIC (~11s faster).
* Some benchmarks run faster under PIC, most are slower
* The difference in time taken (apart from the early and mperm) is at most 3s, and quite frequently much less.

From this, I think we can safely say that PIC code doesn't really make any serious difference to the performance of Cyclone, at least according to the ecraven benchmarks.

[results.Cyclone.txt](https://github.com/justinethier/cyclone/files/725925/results.Cyclone.txt)

**Comment by justinethier** [comment]
@kozross - Thanks for putting this together. Let me spend some time going over this, but I do think import is an important feature that will have to be prioritized soon.

**Comment by kozross** [comment]
@justinethier I agree - without a REPL-capable ``import``, ``icyc`` is quite hard to use for the reasons most people use REPLs.

**Comment by justinethier** [comment]
Another thought - `libcyclone.a` could still be linked statically so it does not need to be compiled with PIC. That could mitigate some performance concerns.

**Comment by kozross** [comment]
I agree, given that (as far as I understand it) this is the compiler core, which we're going to need available in the interpreter in any case.

**Comment by justinethier** [comment]
Trying to work through the best way to integrate `-fPIC`.

Also there is a failing test case from Arthur:

    cyclone> (import (iset))             
    iset/base.so: undefined symbol: __glo_bit_91set_127_srfi_60
    (%import ((iset)))Error: Unable to import library: "iset/base.so"

**Comment by justinethier** [comment]
This was done as part of 0.5
